---
- name: old packages are removed
  become: true
  package:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: required packages are installed
  become: true
  package:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: docker gpg key is added
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: docker repositories are added
  become: true
  apt_repository:
    filename: docker
    update_cache: true
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian buster stable"

- name: docker is installed
  become: true
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      #- gcc
      #- python-devel
      #- python-pip
      #- python-requests

- name: docker is enabled
  become: true
  systemd:
    name: docker
    enabled: true
    state: started

#- name: docker-compose is installed
#  become: true
#  get_url:
#    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
#    dest: /usr/local/bin/docker-compose
#    mode: 0755
#
#- name: make docker-compose $PATH agnostic
#  become: true
#  file:
#    src: /usr/local/bin/docker-compose
#    dest: /usr/bin/docker-compose
#    state: link
#
#- name: required pip packages are installed
#  become: true
#  pip:
#    name:
#      - docker
#      - docker-compose
#      - zipp
...
