---
- name: old packages are removed
  become: true
  package:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

- name: required packages are installed
  become: true
  package:
    state: present
    name:
      - python3
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: docker repositories are added
  become: true
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: docker is installed
  become: true
  package:
    state: present
    name:
      - gcc
      - python-devel
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python-pip
      - python-requests

- name: docker is enabled
  become: true
  systemd:
    name: docker
    enabled: true
    state: started

- name: required pip packages are installed
  become: true
  pip:
    name:
      - docker
      - pyyaml
      - docker-compose
...
